### ISSUE TITLE
【compile Error】 swanky contract compile mytoken -v

### ISSUE THREAD

**Issue by mashharuki** [AstarNetwork/swanky-cli#58]
I trying to develop token dapp (psp22) with swanky.

I create template project with `swanky init` command.

And I tried compile contract but bellow error occured.

why??

```bash
swanky contract compile mytoken -v
```

```bash
======== Found contracts ========
        mytoken
======== Compiling mytoken ========
warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
ERROR: Error invoking `cargo metadata`

Caused by:
    `cargo metadata` exited with an error: warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
    warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
        Updating crates.io index
    error: failed to get `ink_engine` as a dependency of package `mytoken v0.1.0 (/Users/harukikondo/git/Astar-FT/mytoken/contracts/mytoken)`
    
    Caused by:
      failed to load source for dependency `ink_engine`
    
    Caused by:
      Unable to update registry `crates-io`
    
    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`
    
    Caused by:
      process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 255)
      --- stderr
      error: cannot open 'FETCH_HEAD': Permission denied
Error: Command failed: cargo +nightly contract build --manifest-path contracts/mytoken/Cargo.toml 
warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
ERROR: Error invoking `cargo metadata`

Caused by:
    `cargo metadata` exited with an error: warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
    warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
        Updating crates.io index
    error: failed to get `ink_engine` as a dependency of package `mytoken v0.1.0 (/Users/harukikondo/git/Astar-FT/mytoken/contracts/mytoken)`
    
    Caused by:
      failed to load source for dependency `ink_engine`
    
    Caused by:
      Unable to update registry `crates-io`
    
    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`
    
    Caused by:
      process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 255)
      --- stderr
      error: cannot open 'FETCH_HEAD': Permission denied

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at main (/Users/harukikondo/git/Astar-FT/mytoken/node_modules/@supercolony/typechain-compiler/index.ts:88:12)
    at Object.<anonymous> (/Users/harukikondo/git/Astar-FT/mytoken/node_modules/@supercolony/typechain-compiler/index.ts:143:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/Users/harukikondo/git/Astar-FT/mytoken/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/harukikondo/git/Astar-FT/mytoken/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(156) [Uint8Array] [
       27,  91,  50, 109,  50,  48,  50,  50,  45,  49,  50,  45,
       50,  48,  84,  49,  51,  58,  48,  57,  58,  49,  48,  46,
       52,  53,  51,  48,  57,  56,  90,  27,  91,  48, 109,  32,
       27,  91,  51,  50, 109,  32,  73,  78,  70,  79,  27,  91,
       48, 109,  32,  27,  91,  50, 109,  99,  97, 114, 103, 111,
       95,  99, 111, 110, 116, 114,  97,  99, 116,  58,  58,  99,
      114,  97, 116, 101,  95, 109, 101, 116,  97, 100,  97, 116,
       97,  27,  91,  48, 109,  27,  91,  50, 109,  58,  27,  91,
       48, 109,  32,  70,
      ... 56 more items
    ],
    Buffer(1336) [Uint8Array] [
      119,  97, 114, 110, 105, 110, 103,  58,  32,  66, 111, 116,
      104,  32,  96,  47,  85, 115, 101, 114, 115,  47, 104,  97,
      114, 117, 107, 105, 107, 111, 110, 100, 111,  47,  46,  99,
       97, 114, 103, 111,  47,  99, 111, 110, 102, 105, 103,  96,
       32,  97, 110, 100,  32,  96,  47,  85, 115, 101, 114, 115,
       47, 104,  97, 114, 117, 107, 105, 107, 111, 110, 100, 111,
       47,  46,  99,  97, 114, 103, 111,  47,  99, 111, 110, 102,
      105, 103,  46, 116, 111, 109, 108,  96,  32, 101, 120, 105,
      115, 116,  46,  32,
      ... 1236 more items
    ]
  ],
  pid: 5852,
  stdout: Buffer(156) [Uint8Array] [
     27,  91,  50, 109,  50,  48,  50,  50,  45,  49,  50,  45,
     50,  48,  84,  49,  51,  58,  48,  57,  58,  49,  48,  46,
     52,  53,  51,  48,  57,  56,  90,  27,  91,  48, 109,  32,
     27,  91,  51,  50, 109,  32,  73,  78,  70,  79,  27,  91,
     48, 109,  32,  27,  91,  50, 109,  99,  97, 114, 103, 111,
     95,  99, 111, 110, 116, 114,  97,  99, 116,  58,  58,  99,
    114,  97, 116, 101,  95, 109, 101, 116,  97, 100,  97, 116,
     97,  27,  91,  48, 109,  27,  91,  50, 109,  58,  27,  91,
     48, 109,  32,  70,
    ... 56 more items
  ],
  stderr: Buffer(1336) [Uint8Array] [
    119,  97, 114, 110, 105, 110, 103,  58,  32,  66, 111, 116,
    104,  32,  96,  47,  85, 115, 101, 114, 115,  47, 104,  97,
    114, 117, 107, 105, 107, 111, 110, 100, 111,  47,  46,  99,
     97, 114, 103, 111,  47,  99, 111, 110, 102, 105, 103,  96,
     32,  97, 110, 100,  32,  96,  47,  85, 115, 101, 114, 115,
     47, 104,  97, 114, 117, 107, 105, 107, 111, 110, 100, 111,
     47,  46,  99,  97, 114, 103, 111,  47,  99, 111, 110, 102,
    105, 103,  46, 116, 111, 109, 108,  96,  32, 101, 120, 105,
    115, 116,  46,  32,
    ... 1236 more items
  ]
}
✔ Contract compiled successfully
⠋ Copying artifacts[Error: ENOENT: no such file or directory, copyfile '/Users/harukikondo/git/Astar-FT/mytoken/artifacts/mytoken.contract' -> '/Users/harukikondo/git/Astar-FT/mytoken/artifacts/mytoken/1671541750870/mytoken.wasm'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/Users/harukikondo/git/Astar-FT/mytoken/artifacts/mytoken.contract',
  dest: '/Users/harukikondo/git/Astar-FT/mytoken/artifacts/mytoken/1671541750870/mytoken.wasm'
}
✔ Copying artifacts OK
✔ Writing config OK
```

**Comment by mashharuki** [comment]
version info

```bash
@astar-network/swanky-cli/1.0.7 darwin-arm64 node-v18.12.1
cargo-contract 1.5.1-unknown-aarch64-apple-darwin
```

**Comment by mashharuki** [comment]
init comannd's log data is here

```bash
? Which contract language should we use? ink
? Which contract template should we use initially? psp22
? What should we name your initial contract? psp22
? What is your name? mashharuki
? What is your email? 
? Do you want to download Swanky node? Yes
✔ Checking dependencies OK
✔ Copying template files OK
✔ Processing templates OK
✔ Initializing git OK
✔ Downloading Swanky node OK
✔ Installing dependencies OK
✔ Writing config OK
🎉 😎 Swanky project successfully initialised! 😎 🎉
```

**Comment by realtakahashi** [comment]
Thank you for your reporting.
In my case, I could compile psp22 contract with swanky.

I can not understand the cause of your issue clearly,but I think maybe this is your environment issue.
So please let me know your environment.

- Did you already installed binaryen?
- What is your cargo-contract version?
-  Please share the result of the command of "rustup show".

**Comment by mashharuki** [comment]
Thank you for replying!!

> Did you already installed binaryen?
Yes. 

> What is your cargo-contract version?
cargo-contract 1.5.1-unknown-aarch64-apple-darwin

> Please share the result of the command of "rustup show".
```bash
Default host: aarch64-apple-darwin
rustup home:  /Users/harukikondo/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2022-06-30-aarch64-apple-darwin
nightly-2022-07-24-aarch64-apple-darwin
nightly-2022-08-15-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)
bpf

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-aarch64-apple-darwin (default)
rustc 1.68.0-nightly (0468a00ae 2022-12-17)
```

**Comment by mashharuki** [comment]
> Thank you for your reporting. In my case, I could compile psp22 contract with swanky.
> 
> I can not understand the cause of your issue clearly,but I think maybe this is your environment issue. So please let me know your environment.
> 
> * Did you already installed binaryen?
> * What is your cargo-contract version?
> * Please share the result of the command of "rustup show".

Thank you for replying!!

> Did you already installed binaryen?
Yes. 

> What is your cargo-contract version?
cargo-contract 1.5.1-unknown-aarch64-apple-darwin

> Please share the result of the command of "rustup show".
```bash
Default host: aarch64-apple-darwin
rustup home:  /Users/harukikondo/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2022-06-30-aarch64-apple-darwin
nightly-2022-07-24-aarch64-apple-darwin
nightly-2022-08-15-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)
bpf

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-aarch64-apple-darwin (default)
rustc 1.68.0-nightly (0468a00ae 2022-12-17)
```

**Comment by realtakahashi** [comment]
Thank you for sharing your information.
I match my environment to your environment, and I compiled again, but the error did not occurred.

Can you try to execute the commands as following?
```
cd contracts/psp22
cargo +nightly-2022-08-15 contract build
```

**Comment by mashharuki** [comment]
> Thank you for sharing your information. I match my environment to your environment, and I compiled again, but the error did not occurred.
> 
> Can you try to execute the commands as following?
> 
> ```
> cd contracts/psp22
> cargo +nightly-2022-08-15 contract build
> ```

OK. the result of command is below.

```bash
harukikondo@kondouharuakiranoMacBook-Pro mytoken % cargo +nightly-2022-08-15 contract build
warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
2022-12-23T03:04:27.194410Z  INFO cargo_contract::crate_metadata: Fetching cargo metadata for Cargo.toml
ERROR: Error invoking `cargo metadata`

Caused by:
    `cargo metadata` exited with an error: warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
    warning: Both `/Users/harukikondo/.cargo/config` and `/Users/harukikondo/.cargo/config.toml` exist. Using `/Users/harukikondo/.cargo/config`
        Updating crates.io index
    error: failed to get `ink_engine` as a dependency of package `mytoken v0.1.0 (/Users/harukikondo/git/Astar-FT/mytoken/contracts/mytoken)`
    
    Caused by:
      failed to load source for dependency `ink_engine`
    
    Caused by:
      Unable to update registry `crates-io`
    
    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`
    
    Caused by:
      process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 255)
      --- stderr
      error: cannot open 'FETCH_HEAD': Permission denied
```

**Comment by realtakahashi** [comment]
I think if you solve this error, maybe you will able to compile.
When I searched by google the error, some solutions exist. Please check it.
```
error: cannot open 'FETCH_HEAD': Permission denied
```

**Comment by mashharuki** [comment]
> I think if you solve this error, maybe you will able to compile. When I searched by google the error, some solutions exist. Please check it.
> 
> ```
> error: cannot open 'FETCH_HEAD': Permission denied
> ```

thank you!! I will try it!

**Comment by mashharuki** [comment]
@realtakahashi  I made it!!

```bash
warning ../../package.json: No license field
$ mocha -r ts-node/register "test/**/*.test.ts" --exit --timeout 20000


  psp22 test
    ✔ Assigns initial balance
    ✔ Transfer adds amount to destination account (64ms)
    ✔ Can not transfer above the amount (47ms)
    ✔ Can not transfer to hated account (104ms)


  4 passing (1s)

✨  Done in 5.51s.
```

**Comment by mashharuki** [comment]
env info

cargo contract version : cargo-contract 1.5.1-unknown-x86_64-apple-darwin
swanky version: @astar-network/swanky-cli/1.0.7 darwin-x64 node-v18.12.1
nodejs version: v18.12.1

**Comment by mashharuki** [comment]
rustup show result

```bash
Default host: x86_64-apple-darwin
rustup home:  /Users/harukikondo/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2022-06-30-x86_64-apple-darwin
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

**Comment by mashharuki** [comment]
At first I was trying with MacOS with M1 chip, but the error could not be resolved, so I built the environment with normal MacOS and tried it and it worked.

**Comment by mashharuki** [comment]
This issue is resolved , so I closed this.
